version: "3"
services:
  go-web-server:
    container_name: http-ratelimiter
    build: .
    environment:
      - GIN_MODE=release
      - LIMIT_PER_MINUTE=100
      - COOLDOWN_PERIOD_IN_MINUTES=1
      - CLEAN_PERIOD_IN_MINUTES=1
      - NETMASK=24
    restart: on-failure
    ports:
      - "8080:8080"
